# Generated by Django 4.0.3 on 2022-10-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_customervo_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customervo',
            name='phone_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
