# Generated by Django 4.0.3 on 2022-10-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_customervo_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='href',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
