# Generated by Django 4.0.3 on 2022-10-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_automobilevo_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervo',
            name='href',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
