# Generated by Django 4.0.3 on 2022-10-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_customervo_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
