# Generated by Django 4.0.3 on 2022-10-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_alter_automobilevo_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerVO',
            new_name='Customer',
        ),
    ]
