# Generated by Django 4.0.3 on 2022-10-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_rename_customervo_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='href',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
