# Generated by Django 4.0.3 on 2022-10-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0008_remove_customer_href_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceappointment',
            old_name='VIN',
            new_name='automobile',
        ),
        migrations.RenameField(
            model_name='serviceappointment',
            old_name='customer_name',
            new_name='customer',
        ),
    ]
