# Generated by Django 4.0.3 on 2022-10-25 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0009_rename_vin_serviceappointment_automobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='automobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automobile', to='service_rest.automobilevo'),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='service_rest.customer'),
        ),
    ]
